version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers: ["tanmen"]
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
      include: "scope"
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers: ["tanmen"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
      include: "scope"
